#!/usr/bin/env bash
# To install nginx and configure it on a remote server

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'

# Create a basic HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is running
sudo service nginx restart
