#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements

#update package
apt-get update -y

#install nginx web server
apt-get install nginx -y

# allow traffic on port 80
sudo ufw allow 'Nginx HTTP'

#create html file with "Hello world!"
echo "Hello World!" > /var/www/html/index.html

#Ensure Nginx is running
sudo service nginx restart
