#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Modify the sed command to change the redirect URL
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/the_WebDevil permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
