#!/usr/bin/env bash
# script to install and configure HAProxy load balancer
sudo apt-get update
sudo apt-get install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOL
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 600 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend web
	bind *:80
	default_backend web_servers
	
backend web_servers
	balance roundrobin
	server web-01 34.232.69.133:80 check
	server web-02 54.209.193.30:80 check
EOL

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
